### 1、输入您的邮箱发送验证码
POST http://82.157.145.197:8848/user/sentMailLoginAuthCode?mail=请填写您的邮箱


### 2、请填写邮箱和验证码获得token
POST http://82.157.145.197:8848/oauth/token?client_id=lingzhong&client_secret=lingzhong&grant_type=password&username={"userMail":"请填写您的邮箱","checkCode":"请填写验证码","authType":"mail"}
